export const REQUIREMENT_SPEC_ARTIFACTS = [
  "requirement.md",
  "requirement.functional.md",
  "requirement.business.md",
  "requirement.permission.md",
  "requirement.acceptance.md",
  "requirement.non-functional.md",
  "all.state.md",
  "all.process.md",
  "backend.process.md",
  "ddd.md",
  "technology.md",
  "architecture.md",
  "contracts.md",
  "openapi.json",
  "asyncapi.json",
  "authorization.fga",
  "schema.dbml",
  "design.token.json",
  "web.md",
  "web.design.token.json",
  "web.ui.yaml",
  "mini-program.md",
  "mini-program.design.token.json",
  "mini-program.ui.yaml",
  "desktop.md",
  "desktop.design.token.json",
  "desktop.ui.yaml",
  "mobile.md",
  "mobile.design.token.json",
  "mobile.ui.yaml",
  "deployment.md",
  "compose.yml",
  "dev.env",
  "test.env",
  "prod.env",
  "status.json",
];

export const LEGACY_DESIGN_ARTIFACTS = [
  "requirement.md", "process.md", "backend.process.md", "backend.ddd.md",
  "architecture.md", "technology.md", "deployment.md", "authorization.fga",
  "openapi.json", "asyncapi.json", "schema.dbml", "design.token.json",
  "web.md", "web.design.token.json", "web.ui.yaml",
  "mini-program.md", "mini-program.design.token.json", "mini-program.ui.yaml",
  "desktop.md", "desktop.design.token.json", "desktop.ui.yaml",
  "mobile.md", "mobile.design.token.json", "mobile.ui.yaml",
  "test-cases.md", "verification.md",
  "development.compose.yml", "development.env", "test.compose.yml", "test.env",
  "production.compose.yml", "production.env",
];
